name: Selenium Test Pipeline

on: [push, pull_request]

jobs:
  # Step 1: Read createTestData flag from config.yaml
  testDataCheckAndCreation:
    runs-on: windows-latest
    outputs:
      createTestData: ${{ steps.read-flag.outputs.createTestData }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install YAML Dependencies
        run: pip install pyyaml

      - name: Read createTestData Flag (PowerShell)
        id: read-flag
        shell: pwsh
        run: |
          $jsonContent = python -c "import yaml, json; print(json.dumps(yaml.safe_load(open('config.yaml'))))"
          $config = $jsonContent | ConvertFrom-Json
          echo "createTestData=$($config.createTestData)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Show Flag Value
        run: echo "createTestData is ${{ env.createTestData }}"

      - name: Install Dependencies
        if: env.createTestData == 'true'
        run: pip install -r requirements.txt

      - name: Run Test Data Generation (If Flag is True)
        if: env.createTestData == 'true'  # Only runs if the flag is true
        working-directory: metadata_driven
        run: python TestDataGenerationViaMetadata.py

      - name: List Generated Files
        run: dir metadata_driven

      - name: Upload Generated Test Data
        uses: actions/upload-artifact@v4
        with:
          name: generated-trade-data
          path: metadata_driven/trade_data_with_line_numbers.csv


  # Step 2: Test Case Execution (Always Runs)
  testCaseExecution:
    needs: testDataCheckAndCreation
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-html  # Explicitly install pytest-html

      - name: Run Selenium Tests
        run: pytest --html=reports/test_report.html --self-contained-html  # Now pytest-html should work

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: reports/test_report.html


  # Step 3: Data Reconciliation (Runs After Test Execution)
  dataReconciliation:
    needs: testCaseExecution
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Data Reconciliation
        run: echo "Tests completed"


