name: Run Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html  # Install pytest-html for reporting

      - name: Run Selenium Tests with HTML Report
        run: |
          pytest --html=reports/test_report.html || true

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: reports/test_report.html

      - name: Upload Screenshots (on Failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: failed-test-screenshots
          path: screenshots/

      - name: Send Notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"GitHub Actions: Selenium tests completed. Check HTML report & screenshots."}' ${{ secrets.SLACK_WEBHOOK_URL }}
